# Generated by Django 5.1 on 2024-09-02 15:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_categories_alter_restaurant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='', upload_to='Restaurants', verbose_name='Restaurant Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Category ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(related_name='restaurant_categories', to='restaurant.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(max_length=350, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Restaurant ID'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=6, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Dish ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(max_length=750, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(upload_to='Dish', verbose_name='Dish Image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_category', to='restaurant.category', verbose_name='Category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_restaurant', to='restaurant.restaurant', verbose_name='Restaurant')),
            ],
        ),
    ]
